apiVersion: v1
kind: Service
metadata:
  name: postgres  # DNS name
  labels:
    app: postgres
    tier: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:       # postgres Pod Should contain same labels
    app: postgres
    tier: database
  clusterIP: NodePort  # We Use DNS, Thus ClusterIP is not relevant
